# This is a basic workflow that is manually triggered

name: Update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '00 9 * * SAT'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Update-Dependices:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Yarn Setup
      uses: DerYeger/yarn-setup-action@v1.0.1
      with:
        node-version: 16 
    - name: Install Dependencies
      run: yarn
    - name: Update Dependencies
      run: |
        yarn upgrade
        yarn
    - uses: fregante/setup-git-user@v1.1.0
    - name: Commit Changes & Push to Remote Branch
      run: |
        git add -A
        git commit -m "chore: update deps"
        git push -u origin
